apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: tt-payment-service
  name: tt-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tt-payment-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: tt-payment-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1111"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://tt-payment-database:3306/trusticket-payment-db?characterEncoding=UTF-8&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_KAFKA_ADMIN_PROPERTIES_BOOTSTRAP_SERVERS
              value: tt-kafka:19092
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: tt-kafka:19092
          image: sjh9708/trusticket-payment-service:latest
          name: tt-payment-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
