version: "3.7"

networks:
  trusticket-network:
    external: true
    name: trusticket-network
  es-bridge:
    driver: bridge

services:
  tt-elasticsearch:
    build:
      dockerfile: ./Dockerfile
      args:
        VERSION: 8.14.1
    container_name: tt-elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=tt-elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    mem_limit: 2g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - es-bridge
      - trusticket-network


  tt-kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: tt-kibana
    environment:
      SERVER_NAME: tt-kibana
      ELASTICSEARCH_HOSTS: http://tt-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - tt-elasticsearch
    networks:
      - es-bridge
      - trusticket-network
