apiVersion: v1
kind: ConfigMap
metadata:
  name: tt-k8s-configmap
data:
  core-database-server: "172.30.1.29:4003"
  booking-database: "172.30.1.29:4004"  
  payment-database: "172.30.1.29:4005"
  core-database-server-connection-string: "jdbc:mariadb://172.30.1.29:4003/trusticket-core-db?characterEncoding=UTF-8&serverTimezone=UTC"
  booking-database-server-connection-string: "jdbc:mariadb://172.30.1.29:4004/trusticket-booking-db?characterEncoding=UTF-8&serverTimezone=UTC"
  payment-database-server-connection-string: "jdbc:mariadb://172.30.1.29:4005/trusticket-payment-db?characterEncoding=UTF-8&serverTimezone=UTC"
  booking-redis-host: "172.30.1.29"
  booking-redis-port: "6395" 
  elasticsearch-server: "172.30.1.29:9200"
  kafka-bootstrap-server: "172.30.1.29:9092"


