apiVersion: apps/v1  
kind: Deployment     
metadata:
  name: tt-booking-service  
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: tt-booking-service 
  template:  
    metadata:
      labels:
        app: tt-booking-service  
    spec:
      containers:
        - image: sjh9708/trusticket-booking-service:latest  
          name: tt-booking-service  
          ports:
            - containerPort: 8080  
              protocol: TCP   
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: tt-k8s-configmap
                  key: kafka-bootstrap-server
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: tt-k8s-configmap
                  key: booking-database-server-connection-string
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tt-k8s-secret
                  key: booking-database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tt-k8s-secret
                  key: booking-database-password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: tt-k8s-configmap
                  key: booking-redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: tt-k8s-configmap
                  key: booking-redis-port
          resources:
            requests:
              cpu: "500m"         # 최소 0.5 core 사용 요청
              memory: "512Mi"     # 최소 512MB 메모리 요청
            limits:
              cpu: "1000m"         # 최대 1 core 제한
              memory: "1024Mi"     # 최대 1024MB 제한
          livenessProbe:
            httpGet:
              path: /booking/actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5 
          readinessProbe:
            httpGet:
              path: /booking/actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5     
      restartPolicy: Always  
