apiVersion: v1
kind: Service  

metadata:
  name: tt-booking-service  

spec:
  ports:
    - name: "http"        
      port: 18082     
      targetPort: 8080    

  selector:
    app: tt-booking-service  
