version: "3.7"
networks:
  trusticket-network:
    external: true
    name: trusticket-network
services:
  tt-core-database:
    container_name: tt-core-database
    platform: linux/x86_64
    image: mariadb:10.11.2
    environment:
      MYSQL_DATABASE: "trusticket-core-db"
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - 4003:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    networks:
      - trusticket-network

 