version: "3.7"
networks:
  trusticket-network:
    external: true
    name: trusticket-network
services:
  tt-booking-redis:
    image: redis:6.2.6-alpine
    ports:
      - 6395:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    container_name: tt-booking-redis
    volumes: # 마운트할 볼륨 설정
      - ./volumes/redis/data:/data
      - ./volumes/redis/conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - trusticket-network
 