apiVersion: apps/v1  
kind: Deployment     
metadata:
  name: tt-resources-service  
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: tt-resources-service 
  template:  
    metadata:
      labels:
        app: tt-resources-service  
    spec:
      containers:
        - image: sjh9708/trusticket-resources-service:latest
          name: tt-resources-service
          env:
            - name: SPRING_RESOURCES_DIR
              value: storage/upload
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/trusticket/storage/upload
              name: tt-resources-service-pvc
          resources:
            requests:
              cpu: "100m"         # 최소 0.1 core 사용 요청
              memory: "128Mi"     # 최소 128MB 메모리 요청
            limits:
              cpu: "300m"         # 최대 0.3 core 제한
              memory: "512Mi"     # 최대 512MB 제한
          livenessProbe:
            httpGet:
              path: /resources/actuator/health
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /resources/actuator/health
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 5  
      restartPolicy: Always
      volumes:
        - name: tt-resources-service-pvc
          persistentVolumeClaim:
            claimName: tt-resources-service-pvc
